//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiningClient.WcfStyleCalcProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfStyleCalcProxy.MySoapServiceSoap")]
    public interface MySoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calc", ReplyAction="*")]
        int Calc(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CalcAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MySoapServiceSoapChannel : MiningClient.WcfStyleCalcProxy.MySoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySoapServiceSoapClient : System.ServiceModel.ClientBase<MiningClient.WcfStyleCalcProxy.MySoapServiceSoap>, MiningClient.WcfStyleCalcProxy.MySoapServiceSoap {
        
        public MySoapServiceSoapClient() {
        }
        
        public MySoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Calc(int x, int y) {
            return base.Channel.Calc(x, y);
        }
        
        public System.Threading.Tasks.Task<int> CalcAsync(int x, int y) {
            return base.Channel.CalcAsync(x, y);
        }
    }
}
