//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurnWebApp.WcfProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bucket", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole.Models")]
    [System.SerializableAttribute()]
    public partial class Bucket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CoalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Coal {
            get {
                return this.CoalField;
            }
            set {
                if ((object.ReferenceEquals(this.CoalField, value) != true)) {
                    this.CoalField = value;
                    this.RaisePropertyChanged("Coal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfProxy.IBucketService")]
    public interface IBucketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBucketService/GetData", ReplyAction="http://tempuri.org/IBucketService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBucketService/GetData", ReplyAction="http://tempuri.org/IBucketService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBucketService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBucketService/GetDataUsingDataContractResponse")]
        BurnWebApp.WcfProxy.Bucket GetDataUsingDataContract(int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBucketService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IBucketService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BurnWebApp.WcfProxy.Bucket> GetDataUsingDataContractAsync(int size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBucketServiceChannel : BurnWebApp.WcfProxy.IBucketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BucketServiceClient : System.ServiceModel.ClientBase<BurnWebApp.WcfProxy.IBucketService>, BurnWebApp.WcfProxy.IBucketService {
        
        public BucketServiceClient() {
        }
        
        public BucketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BucketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BucketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BucketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public BurnWebApp.WcfProxy.Bucket GetDataUsingDataContract(int size) {
            return base.Channel.GetDataUsingDataContract(size);
        }
        
        public System.Threading.Tasks.Task<BurnWebApp.WcfProxy.Bucket> GetDataUsingDataContractAsync(int size) {
            return base.Channel.GetDataUsingDataContractAsync(size);
        }
    }
}
